DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
baseURL = "caixiongjiang.github.io/" 
dateFormat = "2006-01-02 15:04:05" 
description = "My HomePage Description" # will set 'og:description'
enableEmoji = true 
enableGitInfo = false 
languageCode = "zh-cn" 
theme = "diary" 
title = "ğŸŒ€Jarson Cai's Blog" 

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "perldoc"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[params]
enableMathJax = true 
enableOpenGraph = true 
enableReadingTime = true 
enableTwikoo = true 
favicon = "" 
subtitle = "å¤´è„‘æ˜¯æ—¥ç”¨å“ï¼Œä¸æ˜¯è£…é¥°å“" 
twikooEnvId = "blog-9g6ht92ca9c564c6" 

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[menu.main]]
name = "æ–‡ç« ğŸ“–"
url = "/blog"
weight = 1

[[menu.main]]
name = "åˆ†ç±»ğŸ“Œ"
url = "/categories"
weight = 2

[[menu.main]]
name = "æ ‡ç­¾ğŸ·ï¸"
url = "/tags"
weight = 3

[[menu.main]]
name = "ç³»åˆ—ğŸ“š"
url = "/series"
weight = 4

[[menu.main]]
name = "å½’æ¡£ğŸ“ƒ"
url = "/archive"
weight = 5

[[menu.main]]
name = "å…³äºğŸ‘‹"
url = "/about"
weight = 6

[[menu.main]]
name = "å‹é“¾ğŸ”—"
url = "/friends"
weight = 7

[[menu.main]]
name = "RSSğŸ“¢"
url = "/index.xml"
weight = 8


[[menu.footer]]
name = "GitHub"
url = "https://github.com/caixiongjiang"
weight = 2
[[menu.footer]]
name = "MiFeng"
url = "https://jarson-cai.gitee.io/jarson-cai-blog"
weight = 3
[[menu.footer]]
name = "Email"
url = "nau_cxj@163.com"
weight = 4
[[menu.footer]]
name = "LiKou"
url = "https://leetcode-cn.com/u/cai-xiong-jiang/"
weight = 5
